version: 2

sources:
  - name: raw_greenery
    schema: public
    tables:
      - name: users
      - name: addresses
      - name: events
      - name: orders
      - name: order_items
      - name: products
      - name: promos
